import Foundation

enum Localizer {
    static func text(_ russian: String, _ english: String) -> String {
        switch AppSettings.shared.language {
        case .russian:
            return russian
        case .english:
            return english
        case .german:
            return german[english] ?? english
        case .french:
            return french[english] ?? english
        case .spanish:
            return spanish[english] ?? english
        case .chineseSimplified:
            return chineseSimplified[english] ?? english
        case .chineseTraditional:
            return chineseTraditional[english] ?? english
        case .arabic:
            return arabic[english] ?? english
        }
    }

    private static let german: [String: String] = [
        "Hotkey conflict": "Tastenkürzel-Konflikt",
        "Area and full-screen hotkeys must be different.": "Tastenkürzel für Bereich und Vollbild müssen unterschiedlich sein.",
        "Area hotkey conflicts with video hotkey.": "Tastenkürzel für Bereich kollidiert mit dem Video-Tastenkürzel.",
        "Full-screen hotkey conflicts with video hotkey.": "Tastenkürzel für Vollbild kollidiert mit dem Video-Tastenkürzel.",
        "Screenshot Error": "Screenshot-Fehler",
        "Video Recording Error": "Videoaufnahme-Fehler",
        "Settings": "Einstellungen",
        "Open screenshots folder": "Screenshot-Ordner öffnen",
        "Open videos folder": "Video-Ordner öffnen",
        "Quit": "Beenden",
        "Cliptara: Ctrl+` area, Ctrl+1 full screen, Ctrl+2 start/stop video": "Cliptara: Strg+` Bereich, Strg+1 Vollbild, Strg+2 Video Start/Stopp",
        "OK": "OK",
        "Choose screenshots folder": "Screenshot-Ordner auswählen",
        "Choose videos folder": "Video-Ordner auswählen",
        "Recording is already in progress.": "Die Aufnahme läuft bereits.",
        "Recording stop is already in progress.": "Die Aufnahme wird bereits gestoppt.",
        "Recording is not running.": "Die Aufnahme läuft nicht.",
        "Screen Recording access is not granted. Enable it in System Settings.": "Kein Zugriff auf Bildschirmaufnahme. Aktivieren Sie ihn in den Systemeinstellungen.",
        "Could not find a display to record.": "Kein Bildschirm zum Aufnehmen gefunden.",
        "Could not configure screen capture.": "Bildschirmaufnahme konnte nicht konfiguriert werden.",
        "The video could not be saved correctly. Try recording again.": "Das Video konnte nicht korrekt gespeichert werden. Versuchen Sie es erneut.",
        "System Audio": "Systemton",
        "No Audio": "Ohne Ton",
        "Copy to clipboard": "In Zwischenablage kopieren",
        "Save": "Speichern",
        "Cliptara Settings": "Cliptara Einstellungen",
        "Hotkeys": "Tastenkürzel",
        "Area screenshot:": "Bereichsscreenshot:",
        "Screen screenshot:": "Bildschirmscreenshot:",
        "Video start/stop:": "Video Start/Stopp:",
        "Language:": "Sprache:",
        "Screenshot action:": "Screenshot-Aktion:",
        "Screenshot format:": "Screenshot-Format:",
        "Mute screenshot sound:": "Screenshot-Ton stummschalten:",
        "Video bitrate (kbps):": "Video-Bitrate (kbps):",
        "Video audio:": "Video-Audio:",
        "Screenshots folder:": "Screenshot-Ordner:",
        "Videos folder:": "Video-Ordner:",
        "Choose": "Wählen",
        "Donate": "Spenden",
        "Could not capture selected area screenshot.": "Bereichsscreenshot konnte nicht erstellt werden.",
        "Could not capture full-screen screenshot.": "Vollbild-Screenshot konnte nicht erstellt werden.",
        "Space": "Leertaste"
    ]

    private static let french: [String: String] = [
        "Hotkey conflict": "Conflit de raccourcis",
        "Area and full-screen hotkeys must be different.": "Les raccourcis de zone et de plein écran doivent être différents.",
        "Area hotkey conflicts with video hotkey.": "Le raccourci de zone est en conflit avec le raccourci vidéo.",
        "Full-screen hotkey conflicts with video hotkey.": "Le raccourci plein écran est en conflit avec le raccourci vidéo.",
        "Screenshot Error": "Erreur de capture d'écran",
        "Video Recording Error": "Erreur d'enregistrement vidéo",
        "Settings": "Réglages",
        "Open screenshots folder": "Ouvrir le dossier des captures",
        "Open videos folder": "Ouvrir le dossier des vidéos",
        "Quit": "Quitter",
        "Cliptara: Ctrl+` area, Ctrl+1 full screen, Ctrl+2 start/stop video": "Cliptara : Ctrl+` zone, Ctrl+1 plein écran, Ctrl+2 démarrer/arrêter vidéo",
        "OK": "OK",
        "Choose screenshots folder": "Choisir le dossier des captures",
        "Choose videos folder": "Choisir le dossier des vidéos",
        "Recording is already in progress.": "L'enregistrement est déjà en cours.",
        "Recording stop is already in progress.": "L'arrêt de l'enregistrement est déjà en cours.",
        "Recording is not running.": "L'enregistrement n'est pas en cours.",
        "Screen Recording access is not granted. Enable it in System Settings.": "L'accès à l'enregistrement d'écran n'est pas accordé. Activez-le dans Réglages Système.",
        "Could not find a display to record.": "Impossible de trouver un écran à enregistrer.",
        "Could not configure screen capture.": "Impossible de configurer la capture d'écran.",
        "The video could not be saved correctly. Try recording again.": "La vidéo n'a pas pu être enregistrée correctement. Réessayez.",
        "System Audio": "Audio système",
        "No Audio": "Sans audio",
        "Copy to clipboard": "Copier dans le presse-papiers",
        "Save": "Enregistrer",
        "Cliptara Settings": "Réglages Cliptara",
        "Hotkeys": "Raccourcis",
        "Area screenshot:": "Capture de zone :",
        "Screen screenshot:": "Capture d'écran :",
        "Video start/stop:": "Démarrer/arrêter la vidéo :",
        "Language:": "Langue :",
        "Screenshot action:": "Action de capture :",
        "Screenshot format:": "Format de capture :",
        "Mute screenshot sound:": "Couper le son de capture :",
        "Video bitrate (kbps):": "Débit vidéo (kbps) :",
        "Video audio:": "Audio vidéo :",
        "Screenshots folder:": "Dossier des captures :",
        "Videos folder:": "Dossier des vidéos :",
        "Choose": "Choisir",
        "Donate": "Faire un don",
        "Could not capture selected area screenshot.": "Impossible de capturer la zone sélectionnée.",
        "Could not capture full-screen screenshot.": "Impossible de capturer le plein écran.",
        "Space": "Espace"
    ]

    private static let spanish: [String: String] = [
        "Hotkey conflict": "Conflicto de atajos",
        "Area and full-screen hotkeys must be different.": "Los atajos de área y pantalla completa deben ser diferentes.",
        "Area hotkey conflicts with video hotkey.": "El atajo de área entra en conflicto con el atajo de video.",
        "Full-screen hotkey conflicts with video hotkey.": "El atajo de pantalla completa entra en conflicto con el atajo de video.",
        "Screenshot Error": "Error de captura de pantalla",
        "Video Recording Error": "Error de grabación de video",
        "Settings": "Ajustes",
        "Open screenshots folder": "Abrir carpeta de capturas",
        "Open videos folder": "Abrir carpeta de videos",
        "Quit": "Salir",
        "Cliptara: Ctrl+` area, Ctrl+1 full screen, Ctrl+2 start/stop video": "Cliptara: Ctrl+` área, Ctrl+1 pantalla completa, Ctrl+2 iniciar/detener video",
        "OK": "OK",
        "Choose screenshots folder": "Elegir carpeta de capturas",
        "Choose videos folder": "Elegir carpeta de videos",
        "Recording is already in progress.": "La grabación ya está en curso.",
        "Recording stop is already in progress.": "La detención de la grabación ya está en curso.",
        "Recording is not running.": "La grabación no está en curso.",
        "Screen Recording access is not granted. Enable it in System Settings.": "No se concedió acceso a grabación de pantalla. Actívalo en Ajustes del sistema.",
        "Could not find a display to record.": "No se pudo encontrar una pantalla para grabar.",
        "Could not configure screen capture.": "No se pudo configurar la captura de pantalla.",
        "The video could not be saved correctly. Try recording again.": "No se pudo guardar el video correctamente. Inténtalo de nuevo.",
        "System Audio": "Audio del sistema",
        "No Audio": "Sin audio",
        "Copy to clipboard": "Copiar al portapapeles",
        "Save": "Guardar",
        "Cliptara Settings": "Ajustes de Cliptara",
        "Hotkeys": "Atajos",
        "Area screenshot:": "Captura de área:",
        "Screen screenshot:": "Captura de pantalla:",
        "Video start/stop:": "Iniciar/detener video:",
        "Language:": "Idioma:",
        "Screenshot action:": "Acción de captura:",
        "Screenshot format:": "Formato de captura:",
        "Mute screenshot sound:": "Silenciar sonido de captura:",
        "Video bitrate (kbps):": "Bitrate de video (kbps):",
        "Video audio:": "Audio del video:",
        "Screenshots folder:": "Carpeta de capturas:",
        "Videos folder:": "Carpeta de videos:",
        "Choose": "Elegir",
        "Donate": "Donar",
        "Could not capture selected area screenshot.": "No se pudo capturar el área seleccionada.",
        "Could not capture full-screen screenshot.": "No se pudo capturar la pantalla completa.",
        "Space": "Espacio"
    ]

    private static let chineseSimplified: [String: String] = [
        "Hotkey conflict": "快捷键冲突",
        "Area and full-screen hotkeys must be different.": "区域截图和全屏截图的快捷键不能相同。",
        "Area hotkey conflicts with video hotkey.": "区域截图快捷键与视频快捷键冲突。",
        "Full-screen hotkey conflicts with video hotkey.": "全屏截图快捷键与视频快捷键冲突。",
        "Screenshot Error": "截图错误",
        "Video Recording Error": "视频录制错误",
        "Settings": "设置",
        "Open screenshots folder": "打开截图文件夹",
        "Open videos folder": "打开视频文件夹",
        "Quit": "退出",
        "Cliptara: Ctrl+` area, Ctrl+1 full screen, Ctrl+2 start/stop video": "Cliptara：Ctrl+` 区域截图，Ctrl+1 全屏截图，Ctrl+2 开始/停止录制",
        "OK": "确定",
        "Choose screenshots folder": "选择截图文件夹",
        "Choose videos folder": "选择视频文件夹",
        "Recording is already in progress.": "录制已在进行中。",
        "Recording stop is already in progress.": "停止录制已在进行中。",
        "Recording is not running.": "当前未在录制。",
        "Screen Recording access is not granted. Enable it in System Settings.": "未授予屏幕录制权限。请在系统设置中开启。",
        "Could not find a display to record.": "找不到可录制的显示器。",
        "Could not configure screen capture.": "无法配置屏幕录制。",
        "The video could not be saved correctly. Try recording again.": "视频未能正确保存，请重试。",
        "System Audio": "系统声音",
        "No Audio": "无声音",
        "Copy to clipboard": "复制到剪贴板",
        "Save": "保存",
        "Cliptara Settings": "Cliptara 设置",
        "Hotkeys": "快捷键",
        "Area screenshot:": "区域截图：",
        "Screen screenshot:": "全屏截图：",
        "Video start/stop:": "视频开始/停止：",
        "Language:": "语言：",
        "Screenshot action:": "截图操作：",
        "Screenshot format:": "截图格式：",
        "Mute screenshot sound:": "关闭截图声音：",
        "Video bitrate (kbps):": "视频码率 (kbps)：",
        "Video audio:": "视频音频：",
        "Screenshots folder:": "截图文件夹：",
        "Videos folder:": "视频文件夹：",
        "Choose": "选择",
        "Donate": "捐赠",
        "Could not capture selected area screenshot.": "无法截取所选区域。",
        "Could not capture full-screen screenshot.": "无法截取全屏。",
        "Space": "空格"
    ]

    private static let chineseTraditional: [String: String] = [
        "Hotkey conflict": "快捷鍵衝突",
        "Area and full-screen hotkeys must be different.": "區域截圖與全螢幕截圖的快捷鍵不可相同。",
        "Area hotkey conflicts with video hotkey.": "區域截圖快捷鍵與影片快捷鍵衝突。",
        "Full-screen hotkey conflicts with video hotkey.": "全螢幕截圖快捷鍵與影片快捷鍵衝突。",
        "Screenshot Error": "截圖錯誤",
        "Video Recording Error": "影片錄製錯誤",
        "Settings": "設定",
        "Open screenshots folder": "開啟截圖資料夾",
        "Open videos folder": "開啟影片資料夾",
        "Quit": "結束",
        "Cliptara: Ctrl+` area, Ctrl+1 full screen, Ctrl+2 start/stop video": "Cliptara：Ctrl+` 區域截圖，Ctrl+1 全螢幕截圖，Ctrl+2 開始/停止錄影",
        "OK": "確定",
        "Choose screenshots folder": "選擇截圖資料夾",
        "Choose videos folder": "選擇影片資料夾",
        "Recording is already in progress.": "錄影已在進行中。",
        "Recording stop is already in progress.": "停止錄影已在進行中。",
        "Recording is not running.": "目前未在錄影。",
        "Screen Recording access is not granted. Enable it in System Settings.": "未授予螢幕錄製權限。請在系統設定中開啟。",
        "Could not find a display to record.": "找不到可錄製的顯示器。",
        "Could not configure screen capture.": "無法設定螢幕錄製。",
        "The video could not be saved correctly. Try recording again.": "影片未能正確儲存，請再試一次。",
        "System Audio": "系統音訊",
        "No Audio": "無音訊",
        "Copy to clipboard": "複製到剪貼簿",
        "Save": "儲存",
        "Cliptara Settings": "Cliptara 設定",
        "Hotkeys": "快捷鍵",
        "Area screenshot:": "區域截圖：",
        "Screen screenshot:": "全螢幕截圖：",
        "Video start/stop:": "錄影開始/停止：",
        "Language:": "語言：",
        "Screenshot action:": "截圖動作：",
        "Screenshot format:": "截圖格式：",
        "Mute screenshot sound:": "關閉截圖音效：",
        "Video bitrate (kbps):": "影片位元率 (kbps)：",
        "Video audio:": "影片音訊：",
        "Screenshots folder:": "截圖資料夾：",
        "Videos folder:": "影片資料夾：",
        "Choose": "選擇",
        "Donate": "贊助",
        "Could not capture selected area screenshot.": "無法截取選定區域。",
        "Could not capture full-screen screenshot.": "無法截取全螢幕。",
        "Space": "空白鍵"
    ]

    private static let arabic: [String: String] = [
        "Hotkey conflict": "تعارض في اختصارات لوحة المفاتيح",
        "Area and full-screen hotkeys must be different.": "يجب أن تكون اختصارات لقطة المنطقة ولقطة الشاشة الكاملة مختلفة.",
        "Area hotkey conflicts with video hotkey.": "اختصار لقطة المنطقة يتعارض مع اختصار الفيديو.",
        "Full-screen hotkey conflicts with video hotkey.": "اختصار لقطة الشاشة الكاملة يتعارض مع اختصار الفيديو.",
        "Screenshot Error": "خطأ في لقطة الشاشة",
        "Video Recording Error": "خطأ في تسجيل الفيديو",
        "Settings": "الإعدادات",
        "Open screenshots folder": "فتح مجلد لقطات الشاشة",
        "Open videos folder": "فتح مجلد الفيديوهات",
        "Quit": "إنهاء",
        "Cliptara: Ctrl+` area, Ctrl+1 full screen, Ctrl+2 start/stop video": "Cliptara: ‏Ctrl+` لقطة منطقة، ‏Ctrl+1 لقطة شاشة كاملة، ‏Ctrl+2 بدء/إيقاف الفيديو",
        "OK": "موافق",
        "Choose screenshots folder": "اختر مجلد لقطات الشاشة",
        "Choose videos folder": "اختر مجلد الفيديوهات",
        "Recording is already in progress.": "التسجيل قيد التشغيل بالفعل.",
        "Recording stop is already in progress.": "إيقاف التسجيل قيد التنفيذ بالفعل.",
        "Recording is not running.": "التسجيل غير قيد التشغيل.",
        "Screen Recording access is not granted. Enable it in System Settings.": "لم يتم منح إذن تسجيل الشاشة. فعّله من إعدادات النظام.",
        "Could not find a display to record.": "تعذر العثور على شاشة للتسجيل.",
        "Could not configure screen capture.": "تعذر إعداد التقاط الشاشة.",
        "The video could not be saved correctly. Try recording again.": "تعذر حفظ الفيديو بشكل صحيح. حاول التسجيل مرة أخرى.",
        "System Audio": "صوت النظام",
        "No Audio": "بدون صوت",
        "Copy to clipboard": "نسخ إلى الحافظة",
        "Save": "حفظ",
        "Cliptara Settings": "إعدادات Cliptara",
        "Hotkeys": "اختصارات",
        "Area screenshot:": "لقطة منطقة:",
        "Screen screenshot:": "لقطة شاشة كاملة:",
        "Video start/stop:": "بدء/إيقاف الفيديو:",
        "Language:": "اللغة:",
        "Screenshot action:": "إجراء لقطة الشاشة:",
        "Screenshot format:": "تنسيق لقطة الشاشة:",
        "Mute screenshot sound:": "كتم صوت لقطة الشاشة:",
        "Video bitrate (kbps):": "معدل بت الفيديو (kbps):",
        "Video audio:": "صوت الفيديو:",
        "Screenshots folder:": "مجلد لقطات الشاشة:",
        "Videos folder:": "مجلد الفيديوهات:",
        "Choose": "اختيار",
        "Donate": "تبرع",
        "Could not capture selected area screenshot.": "تعذر التقاط المنطقة المحددة.",
        "Could not capture full-screen screenshot.": "تعذر التقاط الشاشة الكاملة.",
        "Space": "مسافة"
    ]
}
